{{- if .Values.votingService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-service
  labels:
    {{- include "perestroika.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.votingService.replicaCount }}
  selector:
    matchLabels:
      {{- include "perestroika.selectorLabels" . | nindent 6 }}-voting-service
  template:
    metadata:
      labels:
        {{- include "perestroika.selectorLabels" . | nindent 8 }}-voting-service
      annotations:
      {{- with .Values.votingService.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/voting-service/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/voting-service/secrets.yaml") . | sha256sum }}
    spec:
      {{- if .Values.votingService.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.votingService.imagePullSecrets.name }}
      {{- end }}
      serviceAccountName: {{ include "perestroika.serviceAccountName" . }}
      containers:
        - name: voting-service
          image: {{ .Values.votingService.image }}
          imagePullPolicy: {{ .Values.votingService.imageConfig.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          {{- if .Values.gcp.secret.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secrets/google/credentials.json"
          {{- end }}
          {{- $secret_name := "voting-service-secrets" }}
          {{- range $name, $value := .Values.votingService.env.secret }}
          {{- if not (empty $value) }}
          {{- if ne $name "GOOGLE_CREDENTIALS_JSON" }}
            - name: {{ $name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret_name }}
                  key: {{ $name | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: voting-service-config
          volumeMounts:
            {{- if .Values.gcp.secret.enabled }}
            - name: gcs-application-credentials
              mountPath: /etc/secrets/google
            {{- end }}
          resources:
            {{- toYaml .Values.votingService.resources | nindent 12 }}
      {{- with .Values.votingService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.votingService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.votingService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if .Values.gcp.secret.enabled }}
        - name: gcs-application-credentials
          secret:
        {{- if .Values.votingService.env.secret.GOOGLE_CREDENTIALS_JSON }}
            secretName: voting-service-secrets
            items:
            - key: GOOGLE_CREDENTIALS_JSON 
              path: credentials.json
        {{- else }}
            secretName: {{ .Values.gcp.secret.name }}
            items:
            - key: {{ .Values.gcp.secret.key }}
              path: credentials.json
        {{- end }}
        {{- end }}
{{- end }}