{{- if and (.Values.votingService.enabled) (.Values.votingService.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    {{- include "perestroika.labels" . | nindent 4 }}
spec:
  type: {{ .Values.votingService.service.type }}
  ports:
    - port: {{ .Values.votingService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "perestroika.selectorLabels" . | nindent 4 }}-voting-service
{{- end }}