{{- if .Values.emojiService.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  emoji-service-config
  labels:
    {{- include "perestroika.labels" . | nindent 4 }}
data:
{{- range $name, $value := .Values.emojiService.env.open }}
  {{ $name }}: {{ $value | quote }}
{{- end -}}
{{- end }}
