{{- if .Values.emojiService.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: emoji-service-secrets
  labels:
    {{- include "perestroika.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.emojiService.env.secret }}
{{- if not (empty $value) }}
{{- if eq $name "GOOGLE_CREDENTIALS_JSON" }}
  {{ $name }}: {{ $value | quote }}
  {{- else }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
