{{- if and (.Values.emojiWeb.enabled) (.Values.emojiWeb.resources) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: emoji-web
  labels:
    {{- include "perestroika.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: emoji-web
  minReplicas: {{ .Values.emojiWeb.hpa.replicas.min }}
  maxReplicas: {{ .Values.emojiWeb.hpa.replicas.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.emojiWeb.hpa.resources.cpuAverage }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.emojiWeb.hpa.resources.memoryAverage }}
{{- end }}