{{- if and (.Values.emojiWeb.enabled) (.Values.emojiWeb.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: emoji-web
  labels:
    {{- include "perestroika.labels" . | nindent 4 }}
spec:
  type: {{ .Values.emojiWeb.service.type }}
  ports:
    - port: {{ .Values.emojiWeb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "perestroika.selectorLabels" . | nindent 4 }}-emoji-web
{{- end }}