FROM node:16-alpine

WORKDIR /opt/bitcapital

ENV NODE_ENV=development
ENV APP_NAME=emoji-web
ENV SCRIPT=start:debug

COPY package.json .
COPY yarn.lock .
COPY nest-cli.json .
COPY tsconfig.json .

RUN yarn install

COPY . .

CMD yarn ${SCRIPT} ${APP_NAME}