{{- if .Values.konga.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  konga-config
  labels:
    {{- include "perestroika.labels" . | nindent 4 }}
data:
  {{- if .Values.konga.config }}
  PORT: "{{ default 1337 .Values.konga.config.port }}"
  NODE_ENV: {{ default "development" .Values.konga.config.node_env }}
  KONGA_HOOK_TIMEOUT: "{{ default 60000 .Values.konga.config.konga_hook_timeout }}"
  DB_ADAPTER: {{ default "postgres" .Values.konga.config.db_adapter }}
  DB_HOST: {{ default "localhost" .Values.konga.config.db_host }}
  DB_PORT: "{{ default 5432 .Values.konga.config.db_port }}"
  DB_USER: {{ .Values.konga.config.db_user }}
  DB_PASSWORD: {{ .Values.konga.config.db_password }}
  DB_DATABASE: {{ default "konga_database" .Values.konga.config.db_database }}
  DB_PG_SCHEMA: {{ default "public" .Values.konga.config.db_pg_schema }}
  {{- if eq .Values.konga.config.node_env "development" }}
  KONGA_LOG_LEVEL: {{ default "debug" .Values.konga.config.log_level }}
  {{ else if eq .Values.konga.config.node_env "production" }}
  KONGA_LOG_LEVEL: {{ default "warn" .Values.konga.config.log_level }}
  {{- end }}
  KONGA_SEED_USER_DATA_SOURCE_FILE: /data/userdb.data
  KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE: /data/kong_node.data
  {{- end }}
{{- end }}