{{- if .Values.konga.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: konga
  labels:
    {{- include "perestroika.labels" . | nindent 4 }}
spec:
  type: {{ .Values.konga.service.type }}
  ports:
    - port: {{ .Values.konga.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "perestroika.selectorLabels" . | nindent 4 }}-konga
{{- end }}
