apiVersion: skaffold/v2beta19
kind: Config

# profiles: 
profiles:
  # Development
  - name: profile-dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: emoji-service-dev
        context: ../../
        docker:
          dockerfile: apps/emoji-service/Dockerfile.dev
          buildArgs:
            SCRIPT: start:debug
        sync:
          manual:
          # Sync all the TypeScript files that are in the apps folder
          - src: 'apps/**/*.ts'
            dest: .
          # Sync all the TypeScript files that are in the libs folder
          - src: 'libs/**/*.ts'
            dest: .
  # Production:
  - name: profile-prod
    activation:
      - command: run
    build:
      artifacts:
      - image: emoji-service
        context: .
        requires:
        - image: monorepo-base
          alias: MONOREPO_BASE
        docker:
          dockerfile: Dockerfile.prod
    